# Generated by Django 3.0.6 on 2020-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='location',
        ),
        migrations.AddField(
            model_name='search',
            name='loc',
            field=models.TextField(default='San Francisco, CA'),
        ),
    ]
