# Generated by Django 3.0.6 on 2020-06-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200603_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Search'),
        ),
    ]
