# Generated by Django 3.0.6 on 2020-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200615_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
