# Generated by Django 3.0.6 on 2020-06-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('neg', models.FloatField()),
                ('neu', models.FloatField()),
                ('pos', models.FloatField()),
                ('compound', models.FloatField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='search.Search')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
