# Generated by Django 3.0.6 on 2020-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='collector_type',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
