# Generated by Django 3.0.6 on 2020-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysis_collector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
