# Generated by Django 3.0.6 on 2020-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysis_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
