# Generated by Django 3.0.6 on 2020-06-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200611_0445'),
        ('monitor', '0002_monitorcronjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.MonitorCronJob')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Search')),
            ],
        ),
    ]
