# Generated by Django 3.0.6 on 2020-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_cronlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredsearch',
            name='collectors',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='MonitoredCollector',
        ),
    ]
