# Generated by Django 3.0.6 on 2020-06-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitorcronjob_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredsearch',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
