# Generated by Django 3.0.6 on 2020-06-19 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitoredsearch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcronjob',
            name='startdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
